/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CargoRouteImport } from './routes/cargo'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSuperRouteImport } from './routes/_authenticated/super'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedDriverRouteImport } from './routes/_authenticated/driver'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedPortalWalletRouteImport } from './routes/_authenticated/portal/wallet'
import { Route as AuthenticatedPortalToursRouteImport } from './routes/_authenticated/portal/tours'
import { Route as AuthenticatedPortalSupportRouteImport } from './routes/_authenticated/portal/support'
import { Route as AuthenticatedPortalShoppingRouteImport } from './routes/_authenticated/portal/shopping'
import { Route as AuthenticatedPortalSettingsRouteImport } from './routes/_authenticated/portal/settings'
import { Route as AuthenticatedPortalProfileRouteImport } from './routes/_authenticated/portal/profile'
import { Route as AuthenticatedPortalPlacesRouteImport } from './routes/_authenticated/portal/places'
import { Route as AuthenticatedPortalPaymentsRouteImport } from './routes/_authenticated/portal/payments'
import { Route as AuthenticatedPortalNotificationsRouteImport } from './routes/_authenticated/portal/notifications'
import { Route as AuthenticatedPortalMessagesRouteImport } from './routes/_authenticated/portal/messages'
import { Route as AuthenticatedPortalLoyaltyRouteImport } from './routes/_authenticated/portal/loyalty'
import { Route as AuthenticatedPortalHotelsRouteImport } from './routes/_authenticated/portal/hotels'
import { Route as AuthenticatedPortalFlightsRouteImport } from './routes/_authenticated/portal/flights'
import { Route as AuthenticatedPortalDocumentsRouteImport } from './routes/_authenticated/portal/documents'
import { Route as AuthenticatedPortalConciergeRouteImport } from './routes/_authenticated/portal/concierge'
import { Route as AuthenticatedPortalCargoRouteImport } from './routes/_authenticated/portal/cargo'
import { Route as AuthenticatedPortalAnalyticsRouteImport } from './routes/_authenticated/portal/analytics'
import { Route as AuthenticatedAdminTripsRouteImport } from './routes/_authenticated/admin/trips'
import { Route as AuthenticatedAdminTourismRouteImport } from './routes/_authenticated/admin/tourism'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin/support'
import { Route as AuthenticatedAdminShoppingRouteImport } from './routes/_authenticated/admin/shopping'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminIncidentsRouteImport } from './routes/_authenticated/admin/incidents'
import { Route as AuthenticatedAdminFleetRouteImport } from './routes/_authenticated/admin/fleet'
import { Route as AuthenticatedAdminDriversRouteImport } from './routes/_authenticated/admin/drivers'
import { Route as AuthenticatedAdminDispatchRouteImport } from './routes/_authenticated/admin/dispatch'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin/customers'
import { Route as AuthenticatedAdminConciergeRouteImport } from './routes/_authenticated/admin/concierge'
import { Route as AuthenticatedAdminCargoRouteImport } from './routes/_authenticated/admin/cargo'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedPortalTripsIndexRouteImport } from './routes/_authenticated/portal/trips.index'
import { Route as AuthenticatedAdminBookingsIndexRouteImport } from './routes/_authenticated/admin/bookings.index'
import { Route as AuthenticatedPortalTripsIdRouteImport } from './routes/_authenticated/portal/trips.$id'
import { Route as AuthenticatedAdminBookingsIdRouteImport } from './routes/_authenticated/admin/bookings.$id'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoRoute = CargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperRoute = AuthenticatedSuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriverRoute = AuthenticatedDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPortalWalletRoute =
  AuthenticatedPortalWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalToursRoute =
  AuthenticatedPortalToursRouteImport.update({
    id: '/tours',
    path: '/tours',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalSupportRoute =
  AuthenticatedPortalSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalShoppingRoute =
  AuthenticatedPortalShoppingRouteImport.update({
    id: '/shopping',
    path: '/shopping',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalSettingsRoute =
  AuthenticatedPortalSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalProfileRoute =
  AuthenticatedPortalProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalPlacesRoute =
  AuthenticatedPortalPlacesRouteImport.update({
    id: '/places',
    path: '/places',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalPaymentsRoute =
  AuthenticatedPortalPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalNotificationsRoute =
  AuthenticatedPortalNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalMessagesRoute =
  AuthenticatedPortalMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalLoyaltyRoute =
  AuthenticatedPortalLoyaltyRouteImport.update({
    id: '/loyalty',
    path: '/loyalty',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalHotelsRoute =
  AuthenticatedPortalHotelsRouteImport.update({
    id: '/hotels',
    path: '/hotels',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalFlightsRoute =
  AuthenticatedPortalFlightsRouteImport.update({
    id: '/flights',
    path: '/flights',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalDocumentsRoute =
  AuthenticatedPortalDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalConciergeRoute =
  AuthenticatedPortalConciergeRouteImport.update({
    id: '/concierge',
    path: '/concierge',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalCargoRoute =
  AuthenticatedPortalCargoRouteImport.update({
    id: '/cargo',
    path: '/cargo',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalAnalyticsRoute =
  AuthenticatedPortalAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAdminTripsRoute = AuthenticatedAdminTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTourismRoute =
  AuthenticatedAdminTourismRouteImport.update({
    id: '/tourism',
    path: '/tourism',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminShoppingRoute =
  AuthenticatedAdminShoppingRouteImport.update({
    id: '/shopping',
    path: '/shopping',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIncidentsRoute =
  AuthenticatedAdminIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFleetRoute = AuthenticatedAdminFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDriversRoute =
  AuthenticatedAdminDriversRouteImport.update({
    id: '/drivers',
    path: '/drivers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDispatchRoute =
  AuthenticatedAdminDispatchRouteImport.update({
    id: '/dispatch',
    path: '/dispatch',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConciergeRoute =
  AuthenticatedAdminConciergeRouteImport.update({
    id: '/concierge',
    path: '/concierge',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCargoRoute = AuthenticatedAdminCargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPortalTripsIndexRoute =
  AuthenticatedPortalTripsIndexRouteImport.update({
    id: '/trips/',
    path: '/trips/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAdminBookingsIndexRoute =
  AuthenticatedAdminBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPortalTripsIdRoute =
  AuthenticatedPortalTripsIdRouteImport.update({
    id: '/trips/$id',
    path: '/trips/$id',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAdminBookingsIdRoute =
  AuthenticatedAdminBookingsIdRouteImport.update({
    id: '/bookings/$id',
    path: '/bookings/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/cargo': typeof CargoRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/fleet': typeof FleetRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/services': typeof ServicesRoute
  '/shopping': typeof ShoppingRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/super': typeof AuthenticatedSuperRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/cargo': typeof AuthenticatedAdminCargoRoute
  '/admin/concierge': typeof AuthenticatedAdminConciergeRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/dispatch': typeof AuthenticatedAdminDispatchRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/admin/fleet': typeof AuthenticatedAdminFleetRoute
  '/admin/incidents': typeof AuthenticatedAdminIncidentsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/shopping': typeof AuthenticatedAdminShoppingRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/tourism': typeof AuthenticatedAdminTourismRoute
  '/admin/trips': typeof AuthenticatedAdminTripsRoute
  '/portal/analytics': typeof AuthenticatedPortalAnalyticsRoute
  '/portal/cargo': typeof AuthenticatedPortalCargoRoute
  '/portal/concierge': typeof AuthenticatedPortalConciergeRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/flights': typeof AuthenticatedPortalFlightsRoute
  '/portal/hotels': typeof AuthenticatedPortalHotelsRoute
  '/portal/loyalty': typeof AuthenticatedPortalLoyaltyRoute
  '/portal/messages': typeof AuthenticatedPortalMessagesRoute
  '/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/portal/payments': typeof AuthenticatedPortalPaymentsRoute
  '/portal/places': typeof AuthenticatedPortalPlacesRoute
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/portal/shopping': typeof AuthenticatedPortalShoppingRoute
  '/portal/support': typeof AuthenticatedPortalSupportRoute
  '/portal/tours': typeof AuthenticatedPortalToursRoute
  '/portal/wallet': typeof AuthenticatedPortalWalletRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/portal/trips/$id': typeof AuthenticatedPortalTripsIdRoute
  '/admin/bookings/': typeof AuthenticatedAdminBookingsIndexRoute
  '/portal/trips/': typeof AuthenticatedPortalTripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/cargo': typeof CargoRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/fleet': typeof FleetRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/services': typeof ServicesRoute
  '/shopping': typeof ShoppingRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/super': typeof AuthenticatedSuperRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/cargo': typeof AuthenticatedAdminCargoRoute
  '/admin/concierge': typeof AuthenticatedAdminConciergeRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/dispatch': typeof AuthenticatedAdminDispatchRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/admin/fleet': typeof AuthenticatedAdminFleetRoute
  '/admin/incidents': typeof AuthenticatedAdminIncidentsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/shopping': typeof AuthenticatedAdminShoppingRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/tourism': typeof AuthenticatedAdminTourismRoute
  '/admin/trips': typeof AuthenticatedAdminTripsRoute
  '/portal/analytics': typeof AuthenticatedPortalAnalyticsRoute
  '/portal/cargo': typeof AuthenticatedPortalCargoRoute
  '/portal/concierge': typeof AuthenticatedPortalConciergeRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/flights': typeof AuthenticatedPortalFlightsRoute
  '/portal/hotels': typeof AuthenticatedPortalHotelsRoute
  '/portal/loyalty': typeof AuthenticatedPortalLoyaltyRoute
  '/portal/messages': typeof AuthenticatedPortalMessagesRoute
  '/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/portal/payments': typeof AuthenticatedPortalPaymentsRoute
  '/portal/places': typeof AuthenticatedPortalPlacesRoute
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/portal/shopping': typeof AuthenticatedPortalShoppingRoute
  '/portal/support': typeof AuthenticatedPortalSupportRoute
  '/portal/tours': typeof AuthenticatedPortalToursRoute
  '/portal/wallet': typeof AuthenticatedPortalWalletRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/portal/trips/$id': typeof AuthenticatedPortalTripsIdRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsIndexRoute
  '/portal/trips': typeof AuthenticatedPortalTripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/cargo': typeof CargoRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/fleet': typeof FleetRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/services': typeof ServicesRoute
  '/shopping': typeof ShoppingRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/driver': typeof AuthenticatedDriverRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/super': typeof AuthenticatedSuperRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/cargo': typeof AuthenticatedAdminCargoRoute
  '/_authenticated/admin/concierge': typeof AuthenticatedAdminConciergeRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/dispatch': typeof AuthenticatedAdminDispatchRoute
  '/_authenticated/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/_authenticated/admin/fleet': typeof AuthenticatedAdminFleetRoute
  '/_authenticated/admin/incidents': typeof AuthenticatedAdminIncidentsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/shopping': typeof AuthenticatedAdminShoppingRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/tourism': typeof AuthenticatedAdminTourismRoute
  '/_authenticated/admin/trips': typeof AuthenticatedAdminTripsRoute
  '/_authenticated/portal/analytics': typeof AuthenticatedPortalAnalyticsRoute
  '/_authenticated/portal/cargo': typeof AuthenticatedPortalCargoRoute
  '/_authenticated/portal/concierge': typeof AuthenticatedPortalConciergeRoute
  '/_authenticated/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/_authenticated/portal/flights': typeof AuthenticatedPortalFlightsRoute
  '/_authenticated/portal/hotels': typeof AuthenticatedPortalHotelsRoute
  '/_authenticated/portal/loyalty': typeof AuthenticatedPortalLoyaltyRoute
  '/_authenticated/portal/messages': typeof AuthenticatedPortalMessagesRoute
  '/_authenticated/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/_authenticated/portal/payments': typeof AuthenticatedPortalPaymentsRoute
  '/_authenticated/portal/places': typeof AuthenticatedPortalPlacesRoute
  '/_authenticated/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/_authenticated/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/_authenticated/portal/shopping': typeof AuthenticatedPortalShoppingRoute
  '/_authenticated/portal/support': typeof AuthenticatedPortalSupportRoute
  '/_authenticated/portal/tours': typeof AuthenticatedPortalToursRoute
  '/_authenticated/portal/wallet': typeof AuthenticatedPortalWalletRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/_authenticated/portal/trips/$id': typeof AuthenticatedPortalTripsIdRoute
  '/_authenticated/admin/bookings/': typeof AuthenticatedAdminBookingsIndexRoute
  '/_authenticated/portal/trips/': typeof AuthenticatedPortalTripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/cargo'
    | '/contact'
    | '/destinations'
    | '/fleet'
    | '/login'
    | '/privacy'
    | '/procurement'
    | '/services'
    | '/shopping'
    | '/terms'
    | '/track'
    | '/admin'
    | '/dashboard'
    | '/driver'
    | '/portal'
    | '/super'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/cargo'
    | '/admin/concierge'
    | '/admin/customers'
    | '/admin/dispatch'
    | '/admin/drivers'
    | '/admin/fleet'
    | '/admin/incidents'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/shopping'
    | '/admin/support'
    | '/admin/tourism'
    | '/admin/trips'
    | '/portal/analytics'
    | '/portal/cargo'
    | '/portal/concierge'
    | '/portal/documents'
    | '/portal/flights'
    | '/portal/hotels'
    | '/portal/loyalty'
    | '/portal/messages'
    | '/portal/notifications'
    | '/portal/payments'
    | '/portal/places'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/shopping'
    | '/portal/support'
    | '/portal/tours'
    | '/portal/wallet'
    | '/admin/'
    | '/portal/'
    | '/admin/bookings/$id'
    | '/portal/trips/$id'
    | '/admin/bookings/'
    | '/portal/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/cargo'
    | '/contact'
    | '/destinations'
    | '/fleet'
    | '/login'
    | '/privacy'
    | '/procurement'
    | '/services'
    | '/shopping'
    | '/terms'
    | '/track'
    | '/dashboard'
    | '/driver'
    | '/super'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/cargo'
    | '/admin/concierge'
    | '/admin/customers'
    | '/admin/dispatch'
    | '/admin/drivers'
    | '/admin/fleet'
    | '/admin/incidents'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/shopping'
    | '/admin/support'
    | '/admin/tourism'
    | '/admin/trips'
    | '/portal/analytics'
    | '/portal/cargo'
    | '/portal/concierge'
    | '/portal/documents'
    | '/portal/flights'
    | '/portal/hotels'
    | '/portal/loyalty'
    | '/portal/messages'
    | '/portal/notifications'
    | '/portal/payments'
    | '/portal/places'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/shopping'
    | '/portal/support'
    | '/portal/tours'
    | '/portal/wallet'
    | '/admin'
    | '/portal'
    | '/admin/bookings/$id'
    | '/portal/trips/$id'
    | '/admin/bookings'
    | '/portal/trips'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/book'
    | '/cargo'
    | '/contact'
    | '/destinations'
    | '/fleet'
    | '/login'
    | '/privacy'
    | '/procurement'
    | '/services'
    | '/shopping'
    | '/terms'
    | '/track'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/driver'
    | '/_authenticated/portal'
    | '/_authenticated/super'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/cargo'
    | '/_authenticated/admin/concierge'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/dispatch'
    | '/_authenticated/admin/drivers'
    | '/_authenticated/admin/fleet'
    | '/_authenticated/admin/incidents'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/shopping'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/tourism'
    | '/_authenticated/admin/trips'
    | '/_authenticated/portal/analytics'
    | '/_authenticated/portal/cargo'
    | '/_authenticated/portal/concierge'
    | '/_authenticated/portal/documents'
    | '/_authenticated/portal/flights'
    | '/_authenticated/portal/hotels'
    | '/_authenticated/portal/loyalty'
    | '/_authenticated/portal/messages'
    | '/_authenticated/portal/notifications'
    | '/_authenticated/portal/payments'
    | '/_authenticated/portal/places'
    | '/_authenticated/portal/profile'
    | '/_authenticated/portal/settings'
    | '/_authenticated/portal/shopping'
    | '/_authenticated/portal/support'
    | '/_authenticated/portal/tours'
    | '/_authenticated/portal/wallet'
    | '/_authenticated/admin/'
    | '/_authenticated/portal/'
    | '/_authenticated/admin/bookings/$id'
    | '/_authenticated/portal/trips/$id'
    | '/_authenticated/admin/bookings/'
    | '/_authenticated/portal/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  CargoRoute: typeof CargoRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRoute
  FleetRoute: typeof FleetRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcurementRoute: typeof ProcurementRoute
  ServicesRoute: typeof ServicesRoute
  ShoppingRoute: typeof ShoppingRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo': {
      id: '/cargo'
      path: '/cargo'
      fullPath: '/cargo'
      preLoaderRoute: typeof CargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super': {
      id: '/_authenticated/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof AuthenticatedSuperRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/portal/wallet': {
      id: '/_authenticated/portal/wallet'
      path: '/wallet'
      fullPath: '/portal/wallet'
      preLoaderRoute: typeof AuthenticatedPortalWalletRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/tours': {
      id: '/_authenticated/portal/tours'
      path: '/tours'
      fullPath: '/portal/tours'
      preLoaderRoute: typeof AuthenticatedPortalToursRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/support': {
      id: '/_authenticated/portal/support'
      path: '/support'
      fullPath: '/portal/support'
      preLoaderRoute: typeof AuthenticatedPortalSupportRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/shopping': {
      id: '/_authenticated/portal/shopping'
      path: '/shopping'
      fullPath: '/portal/shopping'
      preLoaderRoute: typeof AuthenticatedPortalShoppingRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/settings': {
      id: '/_authenticated/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof AuthenticatedPortalSettingsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/profile': {
      id: '/_authenticated/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof AuthenticatedPortalProfileRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/places': {
      id: '/_authenticated/portal/places'
      path: '/places'
      fullPath: '/portal/places'
      preLoaderRoute: typeof AuthenticatedPortalPlacesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/payments': {
      id: '/_authenticated/portal/payments'
      path: '/payments'
      fullPath: '/portal/payments'
      preLoaderRoute: typeof AuthenticatedPortalPaymentsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/notifications': {
      id: '/_authenticated/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof AuthenticatedPortalNotificationsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/messages': {
      id: '/_authenticated/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof AuthenticatedPortalMessagesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/loyalty': {
      id: '/_authenticated/portal/loyalty'
      path: '/loyalty'
      fullPath: '/portal/loyalty'
      preLoaderRoute: typeof AuthenticatedPortalLoyaltyRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/hotels': {
      id: '/_authenticated/portal/hotels'
      path: '/hotels'
      fullPath: '/portal/hotels'
      preLoaderRoute: typeof AuthenticatedPortalHotelsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/flights': {
      id: '/_authenticated/portal/flights'
      path: '/flights'
      fullPath: '/portal/flights'
      preLoaderRoute: typeof AuthenticatedPortalFlightsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/documents': {
      id: '/_authenticated/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof AuthenticatedPortalDocumentsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/concierge': {
      id: '/_authenticated/portal/concierge'
      path: '/concierge'
      fullPath: '/portal/concierge'
      preLoaderRoute: typeof AuthenticatedPortalConciergeRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/cargo': {
      id: '/_authenticated/portal/cargo'
      path: '/cargo'
      fullPath: '/portal/cargo'
      preLoaderRoute: typeof AuthenticatedPortalCargoRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/analytics': {
      id: '/_authenticated/portal/analytics'
      path: '/analytics'
      fullPath: '/portal/analytics'
      preLoaderRoute: typeof AuthenticatedPortalAnalyticsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/admin/trips': {
      id: '/_authenticated/admin/trips'
      path: '/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AuthenticatedAdminTripsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tourism': {
      id: '/_authenticated/admin/tourism'
      path: '/tourism'
      fullPath: '/admin/tourism'
      preLoaderRoute: typeof AuthenticatedAdminTourismRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/shopping': {
      id: '/_authenticated/admin/shopping'
      path: '/shopping'
      fullPath: '/admin/shopping'
      preLoaderRoute: typeof AuthenticatedAdminShoppingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/incidents': {
      id: '/_authenticated/admin/incidents'
      path: '/incidents'
      fullPath: '/admin/incidents'
      preLoaderRoute: typeof AuthenticatedAdminIncidentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fleet': {
      id: '/_authenticated/admin/fleet'
      path: '/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AuthenticatedAdminFleetRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/drivers': {
      id: '/_authenticated/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AuthenticatedAdminDriversRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dispatch': {
      id: '/_authenticated/admin/dispatch'
      path: '/dispatch'
      fullPath: '/admin/dispatch'
      preLoaderRoute: typeof AuthenticatedAdminDispatchRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/concierge': {
      id: '/_authenticated/admin/concierge'
      path: '/concierge'
      fullPath: '/admin/concierge'
      preLoaderRoute: typeof AuthenticatedAdminConciergeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cargo': {
      id: '/_authenticated/admin/cargo'
      path: '/cargo'
      fullPath: '/admin/cargo'
      preLoaderRoute: typeof AuthenticatedAdminCargoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/portal/trips/': {
      id: '/_authenticated/portal/trips/'
      path: '/trips'
      fullPath: '/portal/trips/'
      preLoaderRoute: typeof AuthenticatedPortalTripsIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/admin/bookings/': {
      id: '/_authenticated/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AuthenticatedAdminBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/portal/trips/$id': {
      id: '/_authenticated/portal/trips/$id'
      path: '/trips/$id'
      fullPath: '/portal/trips/$id'
      preLoaderRoute: typeof AuthenticatedPortalTripsIdRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/admin/bookings/$id': {
      id: '/_authenticated/admin/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AuthenticatedAdminBookingsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCargoRoute: typeof AuthenticatedAdminCargoRoute
  AuthenticatedAdminConciergeRoute: typeof AuthenticatedAdminConciergeRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminDispatchRoute: typeof AuthenticatedAdminDispatchRoute
  AuthenticatedAdminDriversRoute: typeof AuthenticatedAdminDriversRoute
  AuthenticatedAdminFleetRoute: typeof AuthenticatedAdminFleetRoute
  AuthenticatedAdminIncidentsRoute: typeof AuthenticatedAdminIncidentsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminShoppingRoute: typeof AuthenticatedAdminShoppingRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminTourismRoute: typeof AuthenticatedAdminTourismRoute
  AuthenticatedAdminTripsRoute: typeof AuthenticatedAdminTripsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBookingsIdRoute: typeof AuthenticatedAdminBookingsIdRoute
  AuthenticatedAdminBookingsIndexRoute: typeof AuthenticatedAdminBookingsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminCargoRoute: AuthenticatedAdminCargoRoute,
  AuthenticatedAdminConciergeRoute: AuthenticatedAdminConciergeRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminDispatchRoute: AuthenticatedAdminDispatchRoute,
  AuthenticatedAdminDriversRoute: AuthenticatedAdminDriversRoute,
  AuthenticatedAdminFleetRoute: AuthenticatedAdminFleetRoute,
  AuthenticatedAdminIncidentsRoute: AuthenticatedAdminIncidentsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminShoppingRoute: AuthenticatedAdminShoppingRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminTourismRoute: AuthenticatedAdminTourismRoute,
  AuthenticatedAdminTripsRoute: AuthenticatedAdminTripsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBookingsIdRoute: AuthenticatedAdminBookingsIdRoute,
  AuthenticatedAdminBookingsIndexRoute: AuthenticatedAdminBookingsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalAnalyticsRoute: typeof AuthenticatedPortalAnalyticsRoute
  AuthenticatedPortalCargoRoute: typeof AuthenticatedPortalCargoRoute
  AuthenticatedPortalConciergeRoute: typeof AuthenticatedPortalConciergeRoute
  AuthenticatedPortalDocumentsRoute: typeof AuthenticatedPortalDocumentsRoute
  AuthenticatedPortalFlightsRoute: typeof AuthenticatedPortalFlightsRoute
  AuthenticatedPortalHotelsRoute: typeof AuthenticatedPortalHotelsRoute
  AuthenticatedPortalLoyaltyRoute: typeof AuthenticatedPortalLoyaltyRoute
  AuthenticatedPortalMessagesRoute: typeof AuthenticatedPortalMessagesRoute
  AuthenticatedPortalNotificationsRoute: typeof AuthenticatedPortalNotificationsRoute
  AuthenticatedPortalPaymentsRoute: typeof AuthenticatedPortalPaymentsRoute
  AuthenticatedPortalPlacesRoute: typeof AuthenticatedPortalPlacesRoute
  AuthenticatedPortalProfileRoute: typeof AuthenticatedPortalProfileRoute
  AuthenticatedPortalSettingsRoute: typeof AuthenticatedPortalSettingsRoute
  AuthenticatedPortalShoppingRoute: typeof AuthenticatedPortalShoppingRoute
  AuthenticatedPortalSupportRoute: typeof AuthenticatedPortalSupportRoute
  AuthenticatedPortalToursRoute: typeof AuthenticatedPortalToursRoute
  AuthenticatedPortalWalletRoute: typeof AuthenticatedPortalWalletRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedPortalTripsIdRoute: typeof AuthenticatedPortalTripsIdRoute
  AuthenticatedPortalTripsIndexRoute: typeof AuthenticatedPortalTripsIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalAnalyticsRoute: AuthenticatedPortalAnalyticsRoute,
  AuthenticatedPortalCargoRoute: AuthenticatedPortalCargoRoute,
  AuthenticatedPortalConciergeRoute: AuthenticatedPortalConciergeRoute,
  AuthenticatedPortalDocumentsRoute: AuthenticatedPortalDocumentsRoute,
  AuthenticatedPortalFlightsRoute: AuthenticatedPortalFlightsRoute,
  AuthenticatedPortalHotelsRoute: AuthenticatedPortalHotelsRoute,
  AuthenticatedPortalLoyaltyRoute: AuthenticatedPortalLoyaltyRoute,
  AuthenticatedPortalMessagesRoute: AuthenticatedPortalMessagesRoute,
  AuthenticatedPortalNotificationsRoute: AuthenticatedPortalNotificationsRoute,
  AuthenticatedPortalPaymentsRoute: AuthenticatedPortalPaymentsRoute,
  AuthenticatedPortalPlacesRoute: AuthenticatedPortalPlacesRoute,
  AuthenticatedPortalProfileRoute: AuthenticatedPortalProfileRoute,
  AuthenticatedPortalSettingsRoute: AuthenticatedPortalSettingsRoute,
  AuthenticatedPortalShoppingRoute: AuthenticatedPortalShoppingRoute,
  AuthenticatedPortalSupportRoute: AuthenticatedPortalSupportRoute,
  AuthenticatedPortalToursRoute: AuthenticatedPortalToursRoute,
  AuthenticatedPortalWalletRoute: AuthenticatedPortalWalletRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedPortalTripsIdRoute: AuthenticatedPortalTripsIdRoute,
  AuthenticatedPortalTripsIndexRoute: AuthenticatedPortalTripsIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDriverRoute: typeof AuthenticatedDriverRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
  AuthenticatedSuperRoute: typeof AuthenticatedSuperRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDriverRoute: AuthenticatedDriverRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedSuperRoute: AuthenticatedSuperRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  CargoRoute: CargoRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRoute,
  FleetRoute: FleetRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProcurementRoute: ProcurementRoute,
  ServicesRoute: ServicesRoute,
  ShoppingRoute: ShoppingRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
